<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><EnableDefaultCompileItems>false</EnableDefaultCompileItems><AssemblyName>pib-credential-helper</AssemblyName></PropertyGroup><ItemGroup><Compile Include="CredentialHelper.cs"/></ItemGroup></Project>
