// lib/analytics/report-metrics.ts (US-135)
//
// Compute the metric set used by scheduled reports + the HTML email body.
// All numbers derive from real product_sessions / product_events.

import {
  fetchSessions, fetchEvents, sessionDurationSec, isBounce, countBy, channelOf,
  type DateRange,
} from './query'

export const AVAILABLE_METRICS = [
  'sessions',
  'uniqueVisitors',
  'pageviews',
  'bounceRate',
  'avgDurationSec',
  'topSources',
  'topPages',
] as const

export type ReportMetricKey = typeof AVAILABLE_METRICS[number]

export interface ReportData {
  scalar: Record<string, number>
  topSources: Array<{ label: string; count: number }>
  topPages: Array<{ label: string; count: number }>
}

export async function computeReportData(
  propertyId: string,
  range: DateRange,
  metrics: string[],
): Promise<ReportData> {
  const sessions = await fetchSessions(propertyId, range)
  const wantPages = metrics.includes('topPages') || metrics.includes('pageviews')
  const pageviews = wantPages ? await fetchEvents(propertyId, range, '$pageview') : []

  const total = sessions.length
  const scalar: Record<string, number> = {}
  if (metrics.includes('sessions')) scalar.sessions = total
  if (metrics.includes('uniqueVisitors')) scalar.uniqueVisitors = new Set(sessions.map(s => s.distinctId)).size
  if (metrics.includes('pageviews')) scalar.pageviews = sessions.reduce((a, s) => a + s.pageCount, 0)
  if (metrics.includes('bounceRate')) {
    const b = sessions.filter(isBounce).length
    scalar.bounceRate = total > 0 ? Math.round((b / total) * 1000) / 10 : 0
  }
  if (metrics.includes('avgDurationSec')) {
    scalar.avgDurationSec = total > 0
      ? Math.round(sessions.reduce((a, s) => a + sessionDurationSec(s), 0) / total) : 0
  }

  const topSources = metrics.includes('topSources') ? countBy(sessions, s => channelOf(s)).slice(0, 8) : []
  const topPages = metrics.includes('topPages')
    ? countBy(pageviews, e => {
        const url = e.pageUrl ?? (e.properties?.['$current_url'] as string) ?? null
        if (!url) return null
        try { return new URL(url).pathname } catch { return url }
      }).slice(0, 10)
    : []

  return { scalar, topSources, topPages }
}

const METRIC_LABELS: Record<string, string> = {
  sessions: 'Sessions',
  uniqueVisitors: 'Unique Visitors',
  pageviews: 'Pageviews',
  bounceRate: 'Bounce Rate (%)',
  avgDurationSec: 'Avg Session (s)',
}

export function reportToHtml(
  title: string,
  range: DateRange,
  data: ReportData,
): string {
  const rows = Object.entries(data.scalar)
    .map(([k, v]) => `<tr><td style="padding:6px 12px;border-bottom:1px solid #eee">${METRIC_LABELS[k] ?? k}</td><td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:600">${v}</td></tr>`)
    .join('')
  const sources = data.topSources.length
    ? `<h3 style="margin:20px 0 8px">Top Sources</h3><table style="width:100%;border-collapse:collapse">${data.topSources.map(s => `<tr><td style="padding:4px 12px;border-bottom:1px solid #f3f3f3">${s.label}</td><td style="padding:4px 12px;border-bottom:1px solid #f3f3f3;text-align:right">${s.count}</td></tr>`).join('')}</table>`
    : ''
  const pages = data.topPages.length
    ? `<h3 style="margin:20px 0 8px">Top Pages</h3><table style="width:100%;border-collapse:collapse">${data.topPages.map(p => `<tr><td style="padding:4px 12px;border-bottom:1px solid #f3f3f3">${p.label}</td><td style="padding:4px 12px;border-bottom:1px solid #f3f3f3;text-align:right">${p.count}</td></tr>`).join('')}</table>`
    : ''
  return `
  <div style="font-family:system-ui,Arial,sans-serif;max-width:600px;margin:0 auto;color:#1a1a1a">
    <h2 style="margin-bottom:4px">${title}</h2>
    <p style="color:#666;margin-top:0;font-size:13px">${range.from.toISOString().slice(0, 10)} → ${range.to.toISOString().slice(0, 10)}</p>
    <table style="width:100%;border-collapse:collapse;margin-top:12px">${rows}</table>
    ${sources}
    ${pages}
    <p style="color:#999;font-size:11px;margin-top:24px">Generated by Partners in Biz Analytics</p>
  </div>`
}
