import type { YouTubeProductionSkillFamily, YouTubeProductionSkillKey } from './types'

export type YouTubeSkillContract = {
  key: YouTubeProductionSkillKey
  label: string
  family: YouTubeProductionSkillFamily
  bestFor: string
  requiredContext: string[]
  outputArtifacts: string[]
  guardrails: string[]
  policySourceKeys: string[]
  outputPersistence: string
  mutationPolicy: string
  defaultReviewRequired: boolean
}

export const YOUTUBE_SKILL_POLICY_SOURCE_KEYS = [
  'youtube_data_api_upload_private_first',
  'youtube_api_quota_compliance',
  'youtube_altered_synthetic_disclosure',
  'youtube_made_for_kids',
  'youtube_monetization_reused_content',
  'youtube_analytics_reporting_source_confidence',
] as const

const REVIEW_ARTIFACT_PERSISTENCE = 'Save every skill result as pending YouTube agent artifacts and lifecycle comments with created/updated actor metadata; do not silently change publish, schedule, visibility, approval, packet, or release-plan state.'
const REVIEW_ONLY_MUTATION_POLICY = 'Review-only execution. If the model recommends publish-state, schedule, visibility, approval, packet, or release-plan changes, capture the proposed change as a reviewable recommendation artifact/comment only.'

export const YOUTUBE_PRODUCTION_SKILLS: YouTubeSkillContract[] = [
  {
    key: 'youtube-channel-strategy',
    label: 'Channel strategy',
    family: 'strategy',
    bestFor: 'Positioning, pillars, cadence, offers, audience, risks, and operating rules for a channel workspace.',
    requiredContext: ['brand profile', 'client goals', 'audience notes', 'current channel state'],
    outputArtifacts: ['channel strategy artifact', 'pillar map', 'risk register'],
    guardrails: ['No guaranteed reach or monetization claims.', 'No publishing state mutation.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-series-planner',
    label: 'Video ideation',
    family: 'strategy',
    bestFor: 'Generating video ideas, angles, hooks, series candidates, and prioritised production opportunities.',
    requiredContext: ['channel strategy', 'audience', 'offers', 'topic backlog'],
    outputArtifacts: ['video idea set', 'angle map', 'prioritised backlog'],
    guardrails: ['Do not create repetitive low-effort formats without differentiation notes.', 'Recommendations remain suggestions until operator acceptance.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-video-brief',
    label: 'Research brief',
    family: 'production',
    bestFor: 'Turning an approved topic, source, or request into a sourced production research brief.',
    requiredContext: ['video objective', 'audience', 'source material', 'approval policy'],
    outputArtifacts: ['research brief', 'source map', 'evidence checklist'],
    guardrails: ['Mark claims that need evidence.', 'Do not mark client-ready without review.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence', 'youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-research-to-video',
    label: 'Video brief',
    family: 'production',
    bestFor: 'Converting research findings into a concrete video brief, asset checklist, and recommended production route.',
    requiredContext: ['research item', 'audience', 'offer', 'channel strategy'],
    outputArtifacts: ['video brief', 'asset checklist', 'approval checklist'],
    guardrails: ['Treat YouTube search signals as directional, not absolute.', 'Flag unsupported claims for reviewer follow-up.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-script-writer',
    label: 'Script drafting',
    family: 'production',
    bestFor: 'Drafting hooks, outlines, narration, talking points, scene prompts, CTAs, and revision notes.',
    requiredContext: ['approved brief', 'brand voice', 'target duration', 'source evidence'],
    outputArtifacts: ['script draft', 'hook set', 'shot prompt list'],
    guardrails: ['No unsupported factual claims.', 'No client-visible script without review.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-clip-finder',
    label: 'Clipping plan',
    family: 'production',
    bestFor: 'Finding clip candidates from transcripts, source video, podcast, webinar, or long-form material.',
    requiredContext: ['transcript or source ranges', 'target count', 'duration targets', 'brand rules'],
    outputArtifacts: ['clipping plan', 'clip candidate list', 'crop guidance'],
    guardrails: ['Do not use clips without rights/source confirmation.', 'Keep crop guidance reviewable before editing or publishing.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-shorts-packager',
    label: 'Caption generation',
    family: 'packaging',
    bestFor: 'Preparing captions, on-screen text, Shorts text overlays, subtitle handoff notes, and accessibility edits.',
    requiredContext: ['clip candidates or final transcript', 'brand rules', 'format target', 'rights notes'],
    outputArtifacts: ['caption draft', 'overlay text pack', 'accessibility notes'],
    guardrails: ['Require human review for names, numbers, and claims.', 'No rights bypass.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-thumbnail-brief',
    label: 'Thumbnail brief',
    family: 'packaging',
    bestFor: 'Thumbnail concepts, visual hierarchy, variants, likeness/rights notes, and testing rationale.',
    requiredContext: ['brief', 'script', 'title strategy', 'brand rules'],
    outputArtifacts: ['thumbnail creative brief', 'variant list', 'risk notes'],
    guardrails: ['No misleading thumbnail promises.', 'No unapproved likeness use.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-title-metadata',
    label: 'Title/description/tags',
    family: 'packaging',
    bestFor: 'Drafting title variants, descriptions, tags, hashtags, pinned comment starters, and packaging rationale.',
    requiredContext: ['brief', 'script or transcript', 'audience', 'publishing packet'],
    outputArtifacts: ['metadata packet', 'title variants', 'description draft', 'tag set'],
    guardrails: ['No misleading metadata.', 'No public publish state mutation.'],
    policySourceKeys: ['youtube_data_api_upload_private_first', 'youtube_api_quota_compliance'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-captions-chapters',
    label: 'Chapters',
    family: 'packaging',
    bestFor: 'Creating chapter markers, timestamp titles, chapter rationale, and final transcript alignment checks.',
    requiredContext: ['transcript', 'video structure', 'final edit notes'],
    outputArtifacts: ['chapter package', 'timestamp checklist', 'transcript alignment notes'],
    guardrails: ['Require human review for names, numbers, and claims.', 'Keep chapter timestamps as drafts until editor verification.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-ai-disclosure-check',
    label: 'AI disclosure check',
    family: 'readiness',
    bestFor: 'Determining whether realistic altered or synthetic content disclosure is needed.',
    requiredContext: ['assets', 'AI job history', 'voice/image/video generation notes'],
    outputArtifacts: ['disclosure recommendation', 'evidence checklist'],
    guardrails: ['Never suppress realistic synthetic media disclosure.', 'Reviewer must approve final answer.'],
    policySourceKeys: ['youtube_altered_synthetic_disclosure'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-rights-check',
    label: 'Rights check',
    family: 'readiness',
    bestFor: 'Asset rights, source ownership, consent, reuse risk, and missing confirmations.',
    requiredContext: ['asset list', 'source notes', 'client confirmations', 'license evidence'],
    outputArtifacts: ['rights checklist', 'missing evidence list'],
    guardrails: ['Block publish readiness when rights evidence is missing.', 'Do not bypass consent or license uncertainty.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-publish-readiness',
    label: 'Compliance/readiness',
    family: 'readiness',
    bestFor: 'Checking packet readiness, made-for-kids, AI disclosure, rights, metadata, quota, and private-first upload readiness.',
    requiredContext: ['publishing packet', 'gate checks', 'approval policy', 'asset state'],
    outputArtifacts: ['readiness result', 'blocker list', 'handoff checklist'],
    guardrails: ['No autonomous public publishing.', 'Private-first and admin gate remain required.', 'Never approve, reject, schedule, publish, or change visibility.'],
    policySourceKeys: ['youtube_data_api_upload_private_first', 'youtube_api_quota_compliance', 'youtube_made_for_kids'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-analytics-import',
    label: 'Analytics import',
    family: 'analytics',
    bestFor: 'Normalizing API, Reporting API, or manual metrics into labelled snapshots with confidence notes.',
    requiredContext: ['metric source', 'reporting period', 'channel or video id', 'confidence label'],
    outputArtifacts: ['analytics snapshot', 'source confidence note'],
    guardrails: ['Label partial/delayed/manual metrics.', 'No unsupported revenue or reach claims.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-retention-review',
    label: 'Analytics diagnosis',
    family: 'analytics',
    bestFor: 'Diagnosing retention, weak moments, hook fit, CTR mismatch, traffic source changes, and improvement options.',
    requiredContext: ['video metrics', 'transcript', 'timeline notes', 'thumbnail/title packet'],
    outputArtifacts: ['analytics diagnosis', 'performance findings', 'fix list'],
    guardrails: ['Do not over-rank recommendations with thin data.', 'Label metric freshness and confidence.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-next-video-brief',
    label: 'Next-series planning',
    family: 'analytics',
    bestFor: 'Turning analytics, accepted recommendations, and channel strategy into the next series or follow-up production plan.',
    requiredContext: ['analytics findings', 'strategy', 'series context', 'accepted recommendations'],
    outputArtifacts: ['next-series plan', 'next video brief', 'task suggestions'],
    guardrails: ['Recommendations remain suggestions until operator acceptance.', 'Do not create or reprioritise tasks without review.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    outputPersistence: REVIEW_ARTIFACT_PERSISTENCE,
    mutationPolicy: REVIEW_ONLY_MUTATION_POLICY,
    defaultReviewRequired: true,
  },
]

export function getYouTubeSkillContract(key: string): YouTubeSkillContract | undefined {
  return YOUTUBE_PRODUCTION_SKILLS.find((skill) => skill.key === key)
}
