import type { YouTubeProductionSkillKey } from './types'

export type YouTubeSkillContract = {
  key: YouTubeProductionSkillKey
  label: string
  family: 'strategy' | 'production' | 'packaging' | 'readiness' | 'analytics'
  bestFor: string
  requiredContext: string[]
  outputArtifacts: string[]
  guardrails: string[]
  policySourceKeys: string[]
  defaultReviewRequired: boolean
}

export const YOUTUBE_SKILL_POLICY_SOURCE_KEYS = [
  'youtube_data_api_upload_private_first',
  'youtube_api_quota_compliance',
  'youtube_altered_synthetic_disclosure',
  'youtube_made_for_kids',
  'youtube_monetization_reused_content',
  'youtube_analytics_reporting_source_confidence',
] as const

export const YOUTUBE_PRODUCTION_SKILLS: YouTubeSkillContract[] = [
  {
    key: 'youtube-channel-strategy',
    label: 'Channel strategy',
    family: 'strategy',
    bestFor: 'Positioning, pillars, cadence, offers, audience, risks, and operating rules.',
    requiredContext: ['brand profile', 'client goals', 'audience notes', 'current channel state'],
    outputArtifacts: ['channel strategy artifact', 'pillar map', 'risk register'],
    guardrails: ['No guaranteed reach or monetization claims.', 'No publishing state mutation.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-series-planner',
    label: 'Series planner',
    family: 'strategy',
    bestFor: 'Recurring formats, episode templates, seasons, cadence, and continuity rules.',
    requiredContext: ['channel strategy', 'audience', 'offers', 'topic backlog'],
    outputArtifacts: ['series plan', 'episode template', 'topic backlog'],
    guardrails: ['Do not create repetitive low-effort formats without differentiation notes.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-video-brief',
    label: 'Video brief',
    family: 'production',
    bestFor: 'Turning a request, topic, or source into a production brief.',
    requiredContext: ['video objective', 'audience', 'source material', 'approval policy'],
    outputArtifacts: ['video brief', 'asset checklist', 'approval checklist'],
    guardrails: ['Mark claims that need evidence.', 'Do not mark client-ready without review.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-research-to-video',
    label: 'Research to video',
    family: 'production',
    bestFor: 'Converting Research findings into video concepts and recommended briefs.',
    requiredContext: ['research item', 'audience', 'offer', 'channel strategy'],
    outputArtifacts: ['concept set', 'recommended brief', 'source map'],
    guardrails: ['Treat YouTube search signals as directional, not absolute.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-script-writer',
    label: 'Script writer',
    family: 'production',
    bestFor: 'Hooks, outline, script, chapters, and shot prompts.',
    requiredContext: ['approved brief', 'brand voice', 'target duration', 'source evidence'],
    outputArtifacts: ['script package', 'chapter outline', 'shot list'],
    guardrails: ['No unsupported factual claims.', 'No client-visible script without review.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-clip-finder',
    label: 'Clip finder',
    family: 'production',
    bestFor: 'Finding clip candidates from transcripts, source video, podcast, or webinar material.',
    requiredContext: ['transcript or source ranges', 'target count', 'duration targets', 'brand rules'],
    outputArtifacts: ['clip candidate list', 'hook lines', 'crop guidance'],
    guardrails: ['Do not use clips without rights/source confirmation.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-shorts-packager',
    label: 'Shorts packager',
    family: 'packaging',
    bestFor: 'Packaging selected clips into Shorts-ready briefs.',
    requiredContext: ['clip candidates', 'brand rules', 'format target', 'rights notes'],
    outputArtifacts: ['Shorts pack', 'caption text', 'metadata starter'],
    guardrails: ['Flag Shorts over one minute for extra review.', 'No rights bypass.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-thumbnail-brief',
    label: 'Thumbnail brief',
    family: 'packaging',
    bestFor: 'Thumbnail concepts, visual hierarchy, variants, and risk notes.',
    requiredContext: ['brief', 'script', 'title strategy', 'brand rules'],
    outputArtifacts: ['thumbnail creative brief', 'variant list'],
    guardrails: ['No misleading thumbnail promises.', 'No unapproved likeness use.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-title-metadata',
    label: 'Title and metadata',
    family: 'packaging',
    bestFor: 'Titles, descriptions, tags, chapters, and packaging rationale.',
    requiredContext: ['brief', 'script or transcript', 'audience', 'publishing packet'],
    outputArtifacts: ['metadata packet', 'title variants', 'description draft'],
    guardrails: ['No misleading metadata.', 'No public publish state mutation.'],
    policySourceKeys: ['youtube_data_api_upload_private_first', 'youtube_api_quota_compliance'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-captions-chapters',
    label: 'Captions and chapters',
    family: 'packaging',
    bestFor: 'Caption plan, chapter list, timestamps, and accessibility handoff.',
    requiredContext: ['transcript', 'video structure', 'final edit notes'],
    outputArtifacts: ['caption plan', 'chapter package'],
    guardrails: ['Require human review for names, numbers, and claims.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-ai-disclosure-check',
    label: 'AI disclosure check',
    family: 'readiness',
    bestFor: 'Determining whether realistic altered or synthetic content disclosure is needed.',
    requiredContext: ['assets', 'AI job history', 'voice/image/video generation notes'],
    outputArtifacts: ['disclosure recommendation', 'evidence checklist'],
    guardrails: ['Never suppress realistic synthetic media disclosure.', 'Reviewer must approve final answer.'],
    policySourceKeys: ['youtube_altered_synthetic_disclosure'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-rights-check',
    label: 'Rights check',
    family: 'readiness',
    bestFor: 'Asset rights, source ownership, consent, and missing confirmations.',
    requiredContext: ['asset list', 'source notes', 'client confirmations', 'license evidence'],
    outputArtifacts: ['rights checklist', 'missing evidence list'],
    guardrails: ['Block publish readiness when rights evidence is missing.'],
    policySourceKeys: ['youtube_monetization_reused_content'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-publish-readiness',
    label: 'Publish readiness',
    family: 'readiness',
    bestFor: 'Checking packet readiness before manual handoff or private upload.',
    requiredContext: ['publishing packet', 'gate checks', 'approval policy', 'asset state'],
    outputArtifacts: ['readiness result', 'blocker list', 'handoff checklist'],
    guardrails: ['No autonomous public publishing.', 'Private-first and admin gate remain required.'],
    policySourceKeys: ['youtube_data_api_upload_private_first', 'youtube_api_quota_compliance', 'youtube_made_for_kids'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-analytics-import',
    label: 'Analytics import',
    family: 'analytics',
    bestFor: 'Normalizing API, Reporting API, or manual metrics into labelled snapshots.',
    requiredContext: ['metric source', 'reporting period', 'channel or video id', 'confidence label'],
    outputArtifacts: ['analytics snapshot', 'source confidence note'],
    guardrails: ['Label partial/delayed/manual metrics.', 'No unsupported revenue or reach claims.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-retention-review',
    label: 'Retention review',
    family: 'analytics',
    bestFor: 'Explaining weak moments, hook fit, CTR mismatch, and content improvement options.',
    requiredContext: ['video metrics', 'transcript', 'timeline notes', 'thumbnail/title packet'],
    outputArtifacts: ['performance findings', 'fix list'],
    guardrails: ['Do not over-rank recommendations with thin data.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    defaultReviewRequired: true,
  },
  {
    key: 'youtube-next-video-brief',
    label: 'Next video brief',
    family: 'analytics',
    bestFor: 'Turning analytics and series strategy into the next actionable production brief.',
    requiredContext: ['analytics findings', 'strategy', 'series context', 'accepted recommendations'],
    outputArtifacts: ['next video brief', 'task suggestions'],
    guardrails: ['Recommendations remain suggestions until operator acceptance.'],
    policySourceKeys: ['youtube_analytics_reporting_source_confidence'],
    defaultReviewRequired: true,
  },
]

export function getYouTubeSkillContract(key: string): YouTubeSkillContract | undefined {
  return YOUTUBE_PRODUCTION_SKILLS.find((skill) => skill.key === key)
}
