import fs from'node:fs';import os from'node:os';import path from'node:path';import{generateKeyPairSync}from'node:crypto';import{MappingRegistry}from'../../runtime-installers/runtime/bridge';import{executeJob}from'../../runtime-installers/runtime/worker'
import { DeviceApiClient } from '../../runtime-installers/runtime/client'
import { applyHeartbeatData } from '../../runtime-installers/runtime/cli'
it('runs a claimed job only in its contained mapping and retries an output-bound signed completion',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'worker-')),root=path.join(d,'root');fs.mkdirSync(root);const maps=new MappingRegistry(path.join(d,'maps'));maps.map('m',root);const k=generateKeyPairSync('ed25519'),calls:any[]=[];let completes=0;const post=jest.fn(async(p:string,b:any)=>{calls.push([p,b]);if(p.endsWith('/complete')&&completes++===0)return new Response('',{status:503});return new Response('',{status:200})});const hermes=jest.fn(async b=>({ok:true,cwd:b.working_directory}));const result=await executeJob({jobId:'j',requestId:'r',prompt:'p',workspaceId:'w',projectId:'p',mappingId:'m',relativeFolder:'',attempt:2,leaseToken:'lease-token-123'},{deviceId:'d',credentialVersion:2,privateKey:k.privateKey.export({type:'pkcs8',format:'pem'}).toString()},maps,post,hermes);expect(hermes).toHaveBeenCalledWith(expect.objectContaining({working_directory:fs.realpathSync(root)}));expect(completes).toBe(2);expect(result.receipt).toEqual(expect.objectContaining({attempt:2,leaseToken:'lease-token-123',event:'completed',outputBytes:Buffer.byteLength(result.output)}));expect(result.receipt.signature).toBeTruthy();expect(calls[0][1].receipt.event).toBe('accepted')})

it('signs every outbound queue request with a nonce and exact body',async()=>{const keys=generateKeyPairSync('ed25519'),seen:any[]=[];const fetcher=jest.fn(async(url:any,init:any)=>{seen.push([String(url),init]);return new Response(JSON.stringify({data:null}),{status:200,headers:{'content-type':'application/json'}})});const client=new DeviceApiClient('https://partnersinbiz.online',{deviceId:'device-1',credential:'credential-1',credentialVersion:3,privateKey:keys.privateKey.export({type:'pkcs8',format:'pem'}).toString()},fetcher as any,()=>1700000000000,()=> 'nonce-123');await client.post('/api/v1/linked-computers/device-1/runs/claim',{runtimeVersion:'1.0.0'});const [,request]=seen[0],body=request.body,timestamp=request.headers['x-device-timestamp'],signature=request.headers['x-device-signature'];expect(request.headers['x-device-request-id']).toBe('nonce-123');expect(request.headers['x-device-credential']).toBe('credential-1');const payload=`POST\n/api/v1/linked-computers/device-1/runs/claim\n${timestamp}\nnonce-123\n${body}`;expect(require('node:crypto').verify(null,Buffer.from(payload),keys.publicKey,Buffer.from(signature,'base64url'))).toBe(true)})

it('persists mappings in a private registry and removes them cleanly',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'mapping-mode-')),root=path.join(d,'root'),file=path.join(d,'state','mappings.json');fs.mkdirSync(root);const maps=new MappingRegistry(file);maps.map('m',root);expect(fs.statSync(file).mode&0o777).toBe(0o600);expect(maps.status()).toEqual([{mappingId:'m',root:fs.realpathSync(root)}]);maps.unmap('m');expect(maps.status()).toEqual([])})

it('renews the signed lease while Hermes is still running and stops after completion',async()=>{jest.useFakeTimers();const d=fs.mkdtempSync(path.join(os.tmpdir(),'worker-renew-')),root=path.join(d,'root');fs.mkdirSync(root);const maps=new MappingRegistry(path.join(d,'maps'));maps.map('m',root);const k=generateKeyPairSync('ed25519'),events:string[]=[];let finish!:(v:string)=>void;const hermes=()=>new Promise<string>(r=>{finish=r});const post=jest.fn(async(_p:string,b:any)=>{events.push(b.receipt.event);return new Response('',{status:200})});const promise=executeJob({jobId:'j',requestId:'r',prompt:'p',workspaceId:'w',projectId:'p',mappingId:'m',relativeFolder:'',attempt:1,leaseToken:'lease'},{deviceId:'d',credentialVersion:1,privateKey:k.privateKey.export({type:'pkcs8',format:'pem'}).toString()},maps,post,hermes,{progressIntervalMs:1000});await Promise.resolve();await jest.advanceTimersByTimeAsync(3100);expect(events.filter(x=>x==='progress').length).toBeGreaterThanOrEqual(3);finish('done');await promise;const count=events.length;await jest.advanceTimersByTimeAsync(5000);expect(events).toHaveLength(count);jest.useRealTimers()})

it('awaits an in-flight lease renewal before terminal completion',async()=>{jest.useFakeTimers();const d=fs.mkdtempSync(path.join(os.tmpdir(),'renew-race-')),root=path.join(d,'root');fs.mkdirSync(root);const maps=new MappingRegistry(path.join(d,'maps'));maps.map('m',root);const k=generateKeyPairSync('ed25519'),order:string[]=[];let releaseRenew!:(r:Response)=>void,finishHermes!:(v:string)=>void;const post=jest.fn(async(p:string,b:any)=>{if(b.receipt.event==='progress'){order.push('renew-start');return new Promise<Response>(r=>{releaseRenew=r})}if(p.endsWith('/complete'))order.push('complete');return new Response('',{status:200})});const promise=executeJob({jobId:'j',requestId:'r',prompt:'p',workspaceId:'w',projectId:'p',mappingId:'m',relativeFolder:'',attempt:1,leaseToken:'lease'},{deviceId:'d',credentialVersion:1,privateKey:k.privateKey.export({type:'pkcs8',format:'pem'}).toString()},maps,post,()=>new Promise<string>(r=>{finishHermes=r}),{progressIntervalMs:1000});await Promise.resolve();await jest.advanceTimersByTimeAsync(1000);expect(order).toEqual(['renew-start']);finishHermes('done');await Promise.resolve();expect(order).toEqual(['renew-start']);releaseRenew(new Response('',{status:200}));await promise;expect(order).toEqual(['renew-start','complete']);jest.useRealTimers()})

it('applies a route-shaped one-time rotation without retaining transport tokens',async()=>{const current={deviceId:'d',credential:'old',credentialVersion:1,privateKey:'private',transportToken:'legacy'},next=applyHeartbeatData(current,{rotation:{credential:'new',credentialVersion:2,transportToken:'discard'}});expect(next).toEqual({deviceId:'d',credential:'new',credentialVersion:2,privateKey:'private'});expect(applyHeartbeatData(next,{rotation:null})).toBe(next);const fetcher=jest.fn(async()=>new Response('',{status:200})),keys=generateKeyPairSync('ed25519'),client=new DeviceApiClient('https://partnersinbiz.online',{...next,privateKey:keys.privateKey.export({type:'pkcs8',format:'pem'}).toString()},fetcher as any);await client.post('/api/v1/linked-computers/d/runs/claim',{});expect((fetcher.mock.calls[0][1] as any).headers['x-device-credential-version']).toBe('2')})
