import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

describe('VPS skill staging deployment', () => {
  const helper = readFileSync(resolve(process.cwd(), 'scripts/apply-vps-skill-staging.sh'), 'utf8')
  const lib = readFileSync(resolve(process.cwd(), 'scripts/pib-hermes-profile-restart-lib.sh'), 'utf8')
  const sweep = readFileSync(resolve(process.cwd(), 'scripts/pib-hermes-deferred-restart-sweep.sh'), 'utf8')
  const workflow = readFileSync(resolve(process.cwd(), '.github/workflows/sync-vps-skills.yml'), 'utf8')
  const sudoers = readFileSync(resolve(process.cwd(), 'ops/hermes-vps/pib-skill-sync.sudoers'), 'utf8')
  const timer = readFileSync(resolve(process.cwd(), 'ops/hermes-vps/pib-hermes-deferred-restart.timer'), 'utf8')

  it('keeps the privileged installer bounded to an owned, symlink-free staging path', () => {
    expect(helper).toContain('^/srv/hermes-projects/pib-skill-staging/[0-9]+-[0-9]+$')
    expect(helper).toContain("stat -c '%U'")
    expect(helper).toContain('find -P "$staging" -type l')
    expect(helper).toContain('sudo -u hermes env HOME=/var/lib/hermes')
    expect(helper).toContain('PIB_SKILL_RESTART_STABILIZATION_SECONDS:-15')
    expect(helper).toContain('PIB_SKILL_RESTART_GAP_SECONDS:-2')
    expect(helper).toContain('PIB_SKILL_RESTART_DRAIN_SECONDS:-120')
    expect(helper).toContain('pib_hermes_restart_profile_when_idle')
    expect(helper).toContain('deferred')
    expect(helper).toContain('Never force-kill multi-hour runs')
    // Slow/activating units after settle must re-queue, not fail GHA (exit 3).
    expect(helper).toContain('post-restart-not-active')
    expect(helper).toContain('unstable_units')
    expect(helper).not.toMatch(/systemctl is-active "\$\{restarted_units\[@\]\}"/)
    expect(helper).not.toContain('systemctl restart "${active_units[@]}"')
    expect(helper).not.toMatch(/(?:bash|sh|source|\.)\s+"?\$staging/)
  })

  it('never force-restarts busy profiles and defers to the sweeper', () => {
    expect(lib).toContain('pib_hermes_mark_pending_restart')
    expect(lib).toContain('pib_hermes_restart_profile_when_idle')
    expect(lib).toContain('return 2')
    expect(lib).toContain('hermes-restart-pending')
    expect(lib).toContain('PIB_HERMES_SIDECAR_PENDING_DIR')
    expect(sweep).toContain('pib_hermes_restart_profile_when_idle')
    expect(sweep).toContain('SIDECAR_PENDING_DIR')
    expect(sweep).toContain('/var/lib/hermes/hermes-restart-pending')
    expect(timer).toContain('OnUnitActiveSec=2min')
  })

  it('admin sidecar never hard-restarts busy profiles', () => {
    const sidecar = readFileSync(resolve(process.cwd(), 'infra/hermes/admin_sidecar.py'), 'utf8')
    const requestRestart = readFileSync(resolve(process.cwd(), 'scripts/pib-hermes-request-restart.sh'), 'utf8')
    const sudoers = readFileSync(resolve(process.cwd(), 'ops/hermes-vps/pib-hermes-request-restart.sudoers'), 'utf8')
    expect(sidecar).toContain('_restart_profile_detailed')
    expect(sidecar).toContain('_mark_pending_restart')
    expect(sidecar).toContain('hermes-restart-pending')
    expect(sidecar).toContain('auth-provider-upsert')
    expect(sidecar).toContain('Never force-kills busy gateways')
    expect(sidecar).toContain('pib-hermes-request-restart')
    expect(sidecar).toContain('_restart_profile_detailed(profile, "skill-install")')
    expect(sidecar).toContain('_restart_profile_detailed(profile, f"auth-provider-upsert:{provider}")')
    expect(sidecar).toContain('_is_defer_only_restart_reason')
    expect(sidecar).toContain('auth-provider-upsert:')
    expect(sidecar).toContain('defer-only:')
    expect(requestRestart).toContain('pib_hermes_restart_profile_when_idle')
    expect(requestRestart).toContain('auth-provider-*')
    expect(requestRestart).toContain('oauth/token reason never restarts on request path')
    expect(sudoers).toContain('pib-hermes-request-restart')
    expect(sudoers).toContain('hermes ALL=(root) NOPASSWD')
  })

  it('stages outside the private Hermes home and invokes only the root-owned installer', () => {
    expect(workflow).toContain('/srv/hermes-projects/pib-skill-staging/${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}')
    expect(workflow).toContain('local_helper_sha=$(sha256sum scripts/apply-vps-skill-staging.sh')
    expect(workflow).toContain('Root-owned VPS skill installer is not at the reviewed repository version')
    expect(workflow).toContain("sudo /usr/local/sbin/pib-apply-skill-staging '$staging'")
    expect(workflow).not.toContain(':/var/lib/hermes/')
    expect(sudoers).toContain('pib-apply-skill-staging /srv/hermes-projects/pib-skill-staging/*')
    expect(sudoers).not.toContain('NOPASSWD: ALL')
  })
})
