#!/usr/bin/env node
import { createPrivateKey, randomUUID, sign } from 'node:crypto'
import { createServer } from 'node:http'
import { createPairingIdentity, pairingPayload, createReceipt, redactLog, revokeAndCleanup } from './core'

const api=process.env.PIB_API_BASE||'https://partnersinbiz.online'; const hermes=process.env.PIB_LOCAL_HERMES||'http://127.0.0.1:8755'
const store={async put(name:string,value:string){const p=await import('node:child_process');const helper=process.env.PIB_CREDENTIAL_HELPER||'pib-credential-helper';const r=p.spawnSync(helper,['put',name],{input:value,stdio:['pipe','ignore','pipe']});if(r.status)throw new Error('secure credential write failed')},async get(name:string){const {execFileSync}=await import('node:child_process');return execFileSync(process.env.PIB_CREDENTIAL_HELPER||'pib-credential-helper',['get',name],{encoding:'utf8'}).trim()},async clear(){const {execFileSync}=await import('node:child_process');try{execFileSync(process.env.PIB_CREDENTIAL_HELPER||'pib-credential-helper',['clear'])}catch{}}}
async function pair(challengeId:string){process.stdout.write('One-time pairing code: ');const code=await new Promise<string>(r=>process.stdin.once('data',d=>r(String(d).trim())));const id=randomUUID(),keys=createPairingIdentity();const proof=sign(null,Buffer.from(pairingPayload(challengeId,code,id,keys.publicKey)),keys.privateKey).toString('base64url');const res=await fetch(`${api}/api/v1/linked-computers/pairing/exchange`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challengeId,secret:code,deviceId:id,publicKey:keys.publicKey,proof,label:process.env.HOSTNAME||'Linked computer',platform:process.platform==='win32'?'windows':'macos',architecture:process.arch==='arm64'?'arm64':'x64',runtimeVersion:'1.0.0'})});if(!res.ok)throw new Error('pairing denied');const data=(await res.json() as any).data;await store.put('identity',JSON.stringify({...data,privateKey:keys.privateKey.export({type:'pkcs8',format:'pem'})}));await heartbeat(true);console.log('Paired.')}
async function signed(path:string,body:unknown){const i=JSON.parse(await store.get('identity')),raw=JSON.stringify(body),timestamp=String(Date.now()),requestId=randomUUID(),payload=`POST\n${path}\n${timestamp}\n${requestId}\n${raw}`;return fetch(api+path,{method:'POST',headers:{'content-type':'application/json','x-device-id':i.deviceId,'x-device-credential':i.credential,'x-device-credential-version':String(i.credentialVersion),'x-device-timestamp':timestamp,'x-device-request-id':requestId,'x-device-signature':sign(null,Buffer.from(payload),createPrivateKey(i.privateKey)).toString('base64url')},body:raw})}
async function heartbeat(bootstrapTransport=false){const i=JSON.parse(await store.get('identity'));const r=await signed(`/api/v1/linked-computers/${i.deviceId}/heartbeat`,{runtimeVersion:'1.0.0',health:'ok',capabilities:['workspace.execute'],bootstrapTransport});if(!r.ok)throw new Error('heartbeat rejected');const d=(await r.json() as any).data;if(d.transportToken){i.transportToken=d.transportToken;await store.put('identity',JSON.stringify(i))}}
async function bridge(){setInterval(()=>heartbeat().catch(e=>console.error(redactLog(e.message))),60000);createServer(async(req,res)=>{try{const chunks:Buffer[]=[];for await(const c of req)chunks.push(c);const upstream=await fetch(hermes+(req.url||'/'),{method:req.method,headers:{'content-type':'application/json'},body:['GET','HEAD'].includes(req.method||'')?undefined:Buffer.concat(chunks)});const result=await upstream.text(),i=JSON.parse(await store.get('identity'));res.setHeader('x-pib-execution-receipt',Buffer.from(JSON.stringify(createReceipt({deviceId:i.deviceId,targetId:req.headers['x-pib-target-id']||'',machineLabel:process.env.HOSTNAME||'',acceptedAt:new Date().toISOString(),toolStartedAt:new Date().toISOString(),runtimeVersion:'1.0.0',outcome:upstream.ok?'completed':'failed'},createPrivateKey(i.privateKey)))).toString('base64url'));res.statusCode=upstream.status;res.end(result)}catch(e){console.error(redactLog(String(e)));res.statusCode=502;res.end('{"error":"bridge unavailable"}')}}).listen(8766,'127.0.0.1')}
async function main(){const [cmd,...args]=process.argv.slice(2);if(cmd==='pair')return pair(args[args.indexOf('--challenge')+1]);if(cmd==='bridge')return bridge();if(cmd==='revoke')return revokeAndCleanup(async()=>{const i=JSON.parse(await store.get('identity'));const r=await signed(`/api/v1/linked-computers/${i.deviceId}/heartbeat`,{revoke:true});if(!r.ok)throw new Error('offline')},()=>store.clear()).then(x=>{if(x.remoteRevokePending)console.error('Remote revoke pending; local cleanup complete.')});throw new Error('unsupported command')};main().catch(e=>{console.error(redactLog(e.message));process.exitCode=1})
