export type LoopTemplateCategory = 'engineering' | 'evaluation' | 'operations' | 'content' | 'design'

export type LoopTemplateEntry = {
  id: string
  name: string
  sourceSlug: string
  category: LoopTemplateCategory
  summary: string
  pibFit: string
  recommendedOwnerAgentId: string
  recommendedReviewerAgentId: string
  trigger: string
  action: string
  proof: string
  stopCondition: string
  guardrails: string[]
  starterPrompt: string
}

export const LOOP_TEMPLATE_SOURCE = {
  name: 'Forward Future Loop Library',
  repo: 'Forward-Future/loop-library',
  url: 'https://github.com/Forward-Future/loop-library',
  siteUrl: 'https://signals.forwardfuture.ai/loop-library/',
  license: 'MIT',
  checkedAt: '2026-06-20',
  upstreamUpdatedAt: '2026-06-20T18:01:19Z',
  upstreamPushedAt: '2026-06-20T16:27:28Z',
  upstreamTemplateCount: 42,
  note: 'Adapted into PiB-safe loop templates with explicit proof, stop conditions, reviewer routing, and approval gates. Re-check the source repo before expanding the catalog because new loops are being added frequently.',
} as const

export const LOOP_TEMPLATE_LIBRARY: LoopTemplateEntry[] = [
  {
    id: 'fresh-clone-loop',
    name: 'Fresh Clone Loop',
    sourceSlug: 'fresh-clone-loop',
    category: 'engineering',
    summary: 'Repeat clean onboarding from the README until no hidden setup assumptions remain.',
    pibFit: 'Best for new PiB repos, client repo onboarding, and setup docs that must work for agents without local tribal knowledge.',
    recommendedOwnerAgentId: 'theo',
    recommendedReviewerAgentId: 'qa-release',
    trigger: 'A repo, package, or workflow claims to be ready but has not been proven from a clean checkout.',
    action: 'Clone into a disposable environment, follow only documented setup, fix the first missing instruction or setup defect, then restart clean.',
    proof: 'Clean clone log, exact command transcript, failing gap before the fix, passing setup/test/build evidence after the fix.',
    stopCondition: 'Stop when a clean clone reaches the documented success command without undocumented intervention, or when credentials/approval are the only blocker.',
    guardrails: ['Do not use secrets outside approved env passthrough.', 'Do not force-push or discard existing work.', 'Treat production deploys as approval-gated.'],
    starterPrompt: 'Run a fresh-clone verification loop for the target repo. Use only documented setup instructions, capture every missing assumption, patch the smallest setup/docs gap, restart from a clean checkout, and stop only when the documented success command passes or an approval/credential blocker is explicit.',
  },
  {
    id: 'full-product-evaluation-loop',
    name: 'Full Product Evaluation Loop',
    sourceSlug: 'full-product-evaluation-loop',
    category: 'evaluation',
    summary: 'Test every major product capability and fix outcomes below the quality bar.',
    pibFit: 'Good fit for release-readiness passes across Creative Canvas, Book Studio, Life OS, CRM, and selected-org surfaces.',
    recommendedOwnerAgentId: 'qa-release',
    recommendedReviewerAgentId: 'pip',
    trigger: 'A product surface is close to release, or a feature set needs objective acceptance against realistic user scenarios.',
    action: 'Define scenario coverage, run each scenario through browser/API/tests, rank failures by release risk, fix or route defects, and rerun the scenario set.',
    proof: 'Scenario matrix, screenshots or logs, failing/passing tests, linked fixes, remaining risk list, and release/no-go verdict.',
    stopCondition: 'Stop when all required scenarios pass the bar, or remaining gaps are documented as gated decisions with owners.',
    guardrails: ['No production release without explicit approval.', 'Separate quality PASS from business approval.', 'Do not invent telemetry when logs are missing.'],
    starterPrompt: 'Evaluate the product end-to-end with realistic scenarios. Build a scenario matrix first, execute each scenario with real browser/API/test evidence, fix bounded defects when safe, rerun the failed checks, and finish with a pass/no-go verdict plus remaining approval gates.',
  },
  {
    id: 'five-minute-repository-maintainer-loop',
    name: 'Five-Minute Repository Maintainer Loop',
    sourceSlug: 'five-minute-repository-maintainer-loop',
    category: 'engineering',
    summary: 'Keep repository work moving through bounded maintenance threads without interrupting active agents.',
    pibFit: 'Useful for routine development hygiene: stale dirt, failing narrow tests, dependency drift notes, and low-risk cleanup candidates.',
    recommendedOwnerAgentId: 'theo',
    recommendedReviewerAgentId: 'qa-release',
    trigger: 'Scheduled maintainer sweep or Peet asks what low-risk repo work should be cleaned up next.',
    action: 'Inspect current status, pick one high-confidence bounded maintenance task, complete it with checks, and leave bigger/riskier work as tasks.',
    proof: 'Git status before/after, changed files, focused check output, commit reference, and any created follow-up task.',
    stopCondition: 'Stop after one proven maintenance improvement, a no-op report, or a routed blocker; do not expand scope mid-loop.',
    guardrails: ['One bounded task per pass.', 'Do not interrupt or overwrite other agents\' dirty work.', 'Escalate uncertain cleanup instead of guessing.'],
    starterPrompt: 'Run one repository-maintainer pass. Inspect the repo, choose exactly one safe high-value maintenance item, make the smallest useful change, verify it with focused checks, commit it, and route any larger/uncertain work as follow-up tasks.',
  },
  {
    id: 'production-error-sweep',
    name: 'Production Error Sweep',
    sourceSlug: 'production-error-sweep',
    category: 'operations',
    summary: 'Find, fix, and verify actionable production errors.',
    pibFit: 'Best for internal platform health sweeps where logs show repeated 500s or broken cron/API routes.',
    recommendedOwnerAgentId: 'theo',
    recommendedReviewerAgentId: 'qa-release',
    trigger: 'Production logs, health checks, cron output, or Peet reports recurring errors.',
    action: 'Group errors by root cause, reproduce safely, patch the smallest cause, add regression coverage, and verify the endpoint/check path.',
    proof: 'Log sample, reproduction command, regression test, post-fix check output, and rollback/remaining-risk note.',
    stopCondition: 'Stop when the actionable error group is fixed and verified, or when a production/env/secret approval gate blocks further action.',
    guardrails: ['Read logs without exposing secrets.', 'Do not deploy to production without approval.', 'Do not mutate production data unless explicitly approved.'],
    starterPrompt: 'Sweep production/runtime errors for one actionable error family. Preserve log evidence, reproduce the problem safely, patch root cause, add regression coverage, verify the route or cron path, and stop at any production deploy, secret, or destructive-data gate.',
  },
  {
    id: 'test-coverage-loop',
    name: '100% Test Coverage Loop',
    sourceSlug: '100-percent-test-coverage-loop',
    category: 'engineering',
    summary: 'Add meaningful tests until the targeted suite reaches the defined coverage bar.',
    pibFit: 'Useful for risky platform modules where we need high confidence before release: task gates, billing, publishing, auth, and data scope.',
    recommendedOwnerAgentId: 'theo',
    recommendedReviewerAgentId: 'qa-release',
    trigger: 'A module has a coverage target or a regression-prone area lacks objective checks.',
    action: 'Measure coverage, choose the highest-risk uncovered behavior, add meaningful tests, run the suite, and repeat within budget.',
    proof: 'Coverage report, tests added, failing-before/passing-after output when possible, and uncovered-risk note.',
    stopCondition: 'Stop when the target coverage/check bar is met or when remaining uncovered paths are impossible/unsafe without a separate approved task.',
    guardrails: ['Do not chase shallow line coverage at the expense of behavior proof.', 'Keep tests deterministic.', 'Route broad refactors separately.'],
    starterPrompt: 'Run a coverage loop for the target module. Measure current coverage, add behavior-level tests for the riskiest uncovered path, run the suite, repeat within the stated iteration budget, and stop with coverage evidence plus remaining gaps.',
  },
  {
    id: 'seo-geo-visibility-loop',
    name: 'SEO/GEO Visibility Loop',
    sourceSlug: 'seo-geo-visibility-loop',
    category: 'content',
    summary: 'Fix the highest-impact gaps in search and AI-answer visibility.',
    pibFit: 'Maps cleanly to Silas-led SEO sprint improvements and answer-engine visibility checks for PiB/client sites.',
    recommendedOwnerAgentId: 'seo',
    recommendedReviewerAgentId: 'data',
    trigger: 'Search, GSC/PageSpeed/Bing, content, or AI-answer evidence shows a visibility gap.',
    action: 'Rank crawl/index/content/citation/answer-readiness gaps, fix the highest-impact safe item, and record baseline plus retest plan.',
    proof: 'Source metric/link, before/after page evidence, technical/content change, validation output, and next measurement date.',
    stopCondition: 'Stop after the top evidence-backed improvement is shipped/routed, or when client-visible publishing approval is required.',
    guardrails: ['No public publishing without approval.', 'Use source metrics; do not infer rankings.', 'Preserve client org scope.'],
    starterPrompt: 'Run an SEO/GEO visibility loop. Gather source metrics, identify the highest-impact visibility gap, make or draft the smallest safe improvement, record proof and retest criteria, and stop before any public publishing or client-visible gate.',
  },
  {
    id: 'ticket-to-pr-ready-loop',
    name: 'Ticket-to-PR-Ready Loop',
    sourceSlug: 'ticket-to-pr-ready-loop',
    category: 'engineering',
    summary: 'Turn a ticket or complaint into a verified, reviewer-ready pull request or commit.',
    pibFit: 'Good default for Theo implementation tasks created from support tickets, Peet bug reports, or QA failure comments.',
    recommendedOwnerAgentId: 'theo',
    recommendedReviewerAgentId: 'qa-release',
    trigger: 'A support ticket, QA failure, or Peet report describes broken behavior that needs a bounded fix.',
    action: 'Reproduce the issue, isolate root cause, make a minimal patch, add regression coverage, and prepare reviewer evidence.',
    proof: 'Repro evidence, changed files, test output, manual/API verification, commit, and clear reviewer notes.',
    stopCondition: 'Stop when the fix is committed with proof or when reproduction/approval/context is missing and a blocker task is created.',
    guardrails: ['Do not broaden the ticket scope without a new task.', 'Ask for missing reproduction only after checking available evidence.', 'No production release without approval.'],
    starterPrompt: 'Turn the ticket into a reviewer-ready fix. Reproduce the failure, identify root cause, patch the smallest viable path, add regression coverage, verify with real commands or browser/API evidence, commit, and document any blocker precisely.',
  },
  {
    id: 'accessibility-repair-loop',
    name: 'Accessibility Repair Loop',
    sourceSlug: 'accessibility-repair-loop',
    category: 'design',
    summary: 'Find keyboard, screen-reader, low-vision, and interaction barriers, then fix the most harmful first.',
    pibFit: 'Useful for admin/portal modules before release, especially task boards, chats, document review, and creative workspaces.',
    recommendedOwnerAgentId: 'qa-release',
    recommendedReviewerAgentId: 'theo',
    trigger: 'A user flow needs accessibility QA or a component is flagged for keyboard/screen-reader/contrast issues.',
    action: 'Walk the real task with accessibility checks, rank barriers by user harm, fix the highest-impact safe barrier, and retest.',
    proof: 'Checklist results, screenshots/DOM notes, focused test or lint output, before/after behavior, and remaining barriers.',
    stopCondition: 'Stop when the selected barrier is fixed and retested, or when redesign/product approval is needed.',
    guardrails: ['Do not claim full WCAG compliance without full audit scope.', 'Prefer semantic fixes over visual-only patches.', 'Keep visual redesigns gated when large.'],
    starterPrompt: 'Run an accessibility repair loop for the named flow. Complete the real task with keyboard/screen-reader/contrast checks, pick the most harmful barrier, fix it minimally, retest, and report proof plus remaining barriers.',
  },
  {
    id: 'housekeeper-loop',
    name: 'Housekeeper Loop',
    sourceSlug: 'housekeeper-loop',
    category: 'engineering',
    summary: 'Clean a code project one proven, low-risk change at a time without touching uncertain work.',
    pibFit: 'Matches Peet\'s preference to keep PiB worktrees clean without risking other agents\' active changes.',
    recommendedOwnerAgentId: 'pip',
    recommendedReviewerAgentId: 'theo',
    trigger: 'Worktree hygiene sweep, stale artifacts, duplicate files, or low-risk cleanup request.',
    action: 'Inventory dirt/artifacts, classify ownership, clean only safe duplicates or committed stale outputs, and route anything uncertain.',
    proof: 'Before/after git status, file list, cleanup rationale, focused checks when code is touched, and commit or archived path.',
    stopCondition: 'Stop after one safe cleanup batch or when ownership is uncertain and a task/comment is needed.',
    guardrails: ['Never delete another agent/user change without explicit approval.', 'Prefer archive/routing over destructive cleanup when unsure.', 'Stage only owned files for final commits.'],
    starterPrompt: 'Run a housekeeper loop. Inspect worktree/artifact state, identify one safe cleanup batch, avoid uncertain ownership, verify affected code if touched, commit or archive the cleanup, and route unsafe leftovers with clear evidence.',
  },
  {
    id: 'loop-harness-verification-loop',
    name: 'Loop Harness Verification Loop',
    sourceSlug: 'loop-harness-verification-loop',
    category: 'evaluation',
    summary: 'Ship scheduled agent work only after an independent verification pass.',
    pibFit: 'Directly supports PiB verifier-first autonomous work and Quinn review packets before accepting agent outputs.',
    recommendedOwnerAgentId: 'qa-release',
    recommendedReviewerAgentId: 'pip',
    trigger: 'A loop, cron, or autonomous agent produced work that needs independent acceptance before release or closeout.',
    action: 'Read the producer packet, rerun objective checks, inspect artifacts, classify pass/fail/gated outcome, and write review evidence.',
    proof: 'Producer packet, independent check output, artifact links, PASS/PASS_WITH_APPROVAL_REQUIRED/FAIL_REQUEUE/FAIL_BLOCKED verdict.',
    stopCondition: 'Stop when the reviewer verdict is recorded and either accepted, requeued with exact failures, or blocked on authority/approval.',
    guardrails: ['Reviewer must be independent from producer for risky work.', 'Do not treat agent narrative as proof.', 'Escalate approval-sensitive pass separately.'],
    starterPrompt: 'Run a Loop Harness verification pass. Treat producer output as untrusted until verified, rerun objective checks, inspect canonical artifacts, classify PASS/PASS_WITH_APPROVAL_REQUIRED/FAIL_REQUEUE/FAIL_BLOCKED, and record exact evidence.',
  },
  {
    id: 'stale-safe-batch-release-loop',
    name: 'Stale-Safe Batch Release Loop',
    sourceSlug: 'stale-safe-batch-release-loop',
    category: 'operations',
    summary: 'Batch valid changes and release complete artifacts from the latest integrated development line.',
    pibFit: 'Useful before approved PiB production releases so only current, verified development work is promoted.',
    recommendedOwnerAgentId: 'qa-release',
    recommendedReviewerAgentId: 'theo',
    trigger: 'Peet approves a release review or asks what is safe to promote from development.',
    action: 'Sync latest development, exclude stale/unverified work, run release checks, build a release note, and wait for production approval.',
    proof: 'Included/excluded commit list, test/build output, release risk notes, rollback notes, and explicit production approval status.',
    stopCondition: 'Stop at release-ready evidence or a no-go blocker; never promote to production without Peet approval.',
    guardrails: ['Production deploy/merge is approval-gated.', 'Do not include stale or unreviewed work.', 'No force-push/reset recovery.'],
    starterPrompt: 'Run a stale-safe batch release review. Sync development, list candidate changes, exclude stale or unverified work, execute release checks, prepare release notes and rollback notes, and stop before production promotion unless explicit approval exists.',
  },
  {
    id: 'ui-ux-score-loop',
    name: 'UI/UX Score Loop',
    sourceSlug: 'ui-ux-score-loop',
    category: 'design',
    summary: 'Walk a real user task, score each screen, improve weak spots, and retest.',
    pibFit: 'Good for Peet-facing admin surfaces that feel bulky or unclear, like Briefings, Loop Engine, Kanban, and Creative Canvas.',
    recommendedOwnerAgentId: 'qa-release',
    recommendedReviewerAgentId: 'pip',
    trigger: 'A page or flow is functional but confusing, too bulky, or not operator-ready.',
    action: 'Complete the real task, score screens against a stable rubric, improve the weakest high-impact issue, and retest the same task.',
    proof: 'Task path, screen scores, screenshot notes, code/design change, retest scores, and remaining UX debt.',
    stopCondition: 'Stop when the target task reaches the agreed score or when product/brand approval is required.',
    guardrails: ['Do not redesign broad navigation without approval.', 'Preserve existing data/permission gates.', 'Use real task flow evidence, not preference-only critique.'],
    starterPrompt: 'Run a UI/UX Score loop for the selected flow. Complete the real task, score each screen with the same rubric, improve the weakest high-impact issue, retest the task, and finish with before/after evidence plus remaining decisions.',
  },
]

export function loopTemplatesByCategory(category: LoopTemplateCategory): LoopTemplateEntry[] {
  return LOOP_TEMPLATE_LIBRARY.filter((template) => template.category === category)
}

export function getLoopTemplateById(id: string): LoopTemplateEntry | null {
  return LOOP_TEMPLATE_LIBRARY.find((template) => template.id === id) ?? null
}
