import { NextRequest } from 'next/server'
import { adminDb } from '@/lib/firebase/admin'
import { withAuth } from '@/lib/api/auth'
import { apiError } from '@/lib/api/response'
import { analyticsPropertyErrorResponse, requireAnalyticsProperty } from '@/lib/analytics/property-access'
import { computeReportData } from '@/lib/analytics/report-metrics'
import type { DateRange } from '@/lib/analytics/query'
import type { ApiUser } from '@/lib/api/types'
import type { ScheduledReport } from '@/lib/analytics/types'

export const dynamic = 'force-dynamic'
// react-pdf needs the Node runtime (uses Buffer / fontkit).
export const runtime = 'nodejs'

type RouteContext = { params: Promise<{ id: string }> }

const METRIC_LABELS: Record<string, string> = {
  sessions: 'Sessions',
  uniqueVisitors: 'Unique Visitors',
  pageviews: 'Pageviews',
  bounceRate: 'Bounce Rate (%)',
  avgDurationSec: 'Avg Session (s)',
}

/** GET — render the report as a real downloadable PDF. */
export const GET = withAuth('admin', async (_req: NextRequest, user: ApiUser, ctx: unknown) => {
  const { id } = await (ctx as RouteContext).params

  try {
    const snap = await adminDb.collection('product_reports').doc(id).get()
    if (!snap.exists) return apiError('Report not found', 404)
    const report = { id: snap.id, ...snap.data() } as ScheduledReport
    const property = await requireAnalyticsProperty(user, { propertyId: report.propertyId })

    const days = report.frequency === 'weekly' ? 7 : 30
    const range: DateRange = { from: new Date(Date.now() - days * 86400000), to: new Date() }
    const data = await computeReportData(property.id, range, report.metrics)

    // Dynamic import keeps react-pdf out of the edge/client bundle.
    const React = (await import('react')).default
    const { Document, Page, Text, View, StyleSheet, renderToBuffer } = await import('@react-pdf/renderer')

    const styles = StyleSheet.create({
      page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#1a1a1a' },
      title: { fontSize: 18, marginBottom: 4, fontFamily: 'Helvetica-Bold' },
      sub: { fontSize: 10, color: '#666', marginBottom: 16 },
      h3: { fontSize: 13, marginTop: 16, marginBottom: 6, fontFamily: 'Helvetica-Bold' },
      row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottom: '1px solid #eee' },
      label: { color: '#333' },
      value: { fontFamily: 'Helvetica-Bold' },
      foot: { marginTop: 28, fontSize: 9, color: '#999' },
    })

    const scalarRows = Object.entries(data.scalar).map(([k, v]) =>
      React.createElement(View, { style: styles.row, key: k },
        React.createElement(Text, { style: styles.label }, METRIC_LABELS[k] ?? k),
        React.createElement(Text, { style: styles.value }, String(v)),
      ),
    )
    const sourceRows = data.topSources.map((s, i) =>
      React.createElement(View, { style: styles.row, key: `src${i}` },
        React.createElement(Text, { style: styles.label }, s.label),
        React.createElement(Text, { style: styles.value }, String(s.count)),
      ),
    )
    const pageRows = data.topPages.map((p, i) =>
      React.createElement(View, { style: styles.row, key: `pg${i}` },
        React.createElement(Text, { style: styles.label }, p.label),
        React.createElement(Text, { style: styles.value }, String(p.count)),
      ),
    )

    const children: React.ReactElement[] = [
      React.createElement(Text, { style: styles.title, key: 't' }, report.name),
      React.createElement(Text, { style: styles.sub, key: 's' },
        `${range.from.toISOString().slice(0, 10)} to ${range.to.toISOString().slice(0, 10)}`),
      ...scalarRows,
    ]
    if (sourceRows.length) {
      children.push(React.createElement(Text, { style: styles.h3, key: 'hs' }, 'Top Sources'), ...sourceRows)
    }
    if (pageRows.length) {
      children.push(React.createElement(Text, { style: styles.h3, key: 'hp' }, 'Top Pages'), ...pageRows)
    }
    children.push(React.createElement(Text, { style: styles.foot, key: 'f' }, 'Generated by Partners in Biz Analytics'))

    const doc = React.createElement(Document, {},
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      React.createElement(Page as any, { size: 'A4', style: styles.page }, ...children),
    )

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const buffer = await renderToBuffer(doc as any)

    return new Response(new Uint8Array(buffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${report.name.replace(/[^a-z0-9]+/gi, '-')}.pdf"`,
      },
    })
  } catch (e) {
    const propertyError = analyticsPropertyErrorResponse(e)
    if (propertyError) return propertyError
    console.error('[analytics-report-pdf]', e)
    return apiError('Failed to generate PDF', 500)
  }
})
