import type {
  CreativeCanvasProviderKey,
  CreativeCanvasProviderCapability,
} from '@/lib/creative-canvas/types'

export interface CanvasModel {
  id: string
  label: string
  family: string
  featured: boolean
  kind: 'image' | 'video' | 'audio' | 'text'
  providerKey: CreativeCanvasProviderKey
  capabilities: CreativeCanvasProviderCapability[]
  aspectRatios: string[]
  resolutions?: string[]
  durations?: number[]
  supportsAudio?: boolean
  maxBatch: number
  creditCost: number
  execution: 'sync' | 'async'
  description?: string
}

// The real Higgsfield model catalog (matches the higgsfield-generate skill /
// `higgsfield model list`). `id` is the Higgsfield CLI `--model` id so the
// run manifest passes the right model. All Higgsfield models execute
// asynchronously through the Higgsfield runtime / Hermes agent (the web app
// cannot call the Higgsfield CLI directly). `grok-image` is the one optional
// synchronous "fast preview" path (xAI HTTP API) for instant in-node render.
export const CANVAS_MODELS: CanvasModel[] = [
  // ----- Image -----
  {
    id: 'gpt_image_2',
    label: 'GPT Image 2',
    family: 'OpenAI',
    featured: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 7,
    execution: 'async',
    description: 'Default high-fidelity image generation — graphic design, UI, banners, on-image text.',
  },
  {
    id: 'text2image_soul_v2',
    label: 'Higgsfield Soul 2.0',
    family: 'Higgsfield',
    featured: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 8,
    execution: 'async',
    description: 'Aesthetic UGC, fashion editorial, character generation. Accepts a Soul Character reference.',
  },
  {
    id: 'nano_banana_2',
    label: 'Nano Banana 2',
    family: 'Google',
    featured: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 5,
    execution: 'async',
    description: 'Fast everyday default for character / cartoon / animated-style work.',
  },
  {
    id: 'nano_banana_pro',
    label: 'Nano Banana Pro',
    family: 'Google',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 9,
    execution: 'async',
    description: 'Top-tier Nano Banana with extra fidelity on harder briefs.',
  },
  {
    id: 'seedream_4_5',
    label: 'Seedream 4.5',
    family: 'ByteDance',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image'],
    aspectRatios: ['1:1', '9:16', '16:9'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 7,
    execution: 'async',
    description: 'Complex, face-anchored scene edits.',
  },
  {
    id: 'soul_cinema',
    label: 'Soul Cinema',
    family: 'Higgsfield',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image'],
    aspectRatios: ['16:9', '9:16', '1:1', '3:2'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 9,
    execution: 'async',
    description: 'Cinematic stills, film-grade lighting and concept-art mood.',
  },
  {
    id: 'z_image',
    label: 'Z Image',
    family: 'Tongyi-MAI',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image'],
    aspectRatios: ['1:1', '9:16', '16:9'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 3,
    execution: 'async',
    description: 'Fastest in the catalog — drafts and rapid iteration.',
  },
  {
    id: 'flux_2',
    label: 'Flux 2.0',
    family: 'Black Forest Labs',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 6,
    execution: 'async',
    description: 'Precise prompt adherence with pro/flex/max variants.',
  },
  {
    id: 'grok_imagine',
    label: 'Grok Imagine',
    family: 'xAI',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image'],
    aspectRatios: ['1:1', '9:16', '16:9'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 6,
    execution: 'async',
    description: 'Expressive, high-contrast, bold creative outputs (via Higgsfield).',
  },
  {
    id: 'auto',
    label: 'Auto',
    family: 'Higgsfield',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image'],
    aspectRatios: ['1:1', '9:16', '16:9'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 6,
    execution: 'async',
    description: 'Smart routing — picks the best image model from the prompt.',
  },
  // ----- Video -----
  {
    id: 'seedance_2_0',
    label: 'Seedance 2.0',
    family: 'ByteDance',
    featured: true,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 12, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 68,
    execution: 'async',
    description: 'SOTA all-purpose video — crisp, consistent identity, multi-shot.',
  },
  {
    id: 'kling_3',
    label: 'Kling 3.0',
    family: 'Kling',
    featured: true,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [3, 5, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 48,
    execution: 'async',
    description: 'Cheaper Seedance substitute with audio sync and motion transfer.',
  },
  {
    id: 'veo_3_1',
    label: 'Google Veo 3.1',
    family: 'Google',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video'],
    aspectRatios: ['16:9', '9:16'],
    durations: [4, 8],
    supportsAudio: true,
    maxBatch: 2,
    creditCost: 90,
    execution: 'async',
    description: 'Ultra-realistic, top-tier cinematic quality with audio.',
  },
  {
    id: 'wan_2_7',
    label: 'Wan 2.7',
    family: 'Wan',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 40,
    execution: 'async',
    description: 'Synchronized audio with character-consistent video.',
  },
  {
    id: 'minimax_hailuo',
    label: 'Minimax Hailuo',
    family: 'Hailuo',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video'],
    aspectRatios: ['16:9', '9:16'],
    durations: [4, 8],
    supportsAudio: false,
    maxBatch: 4,
    creditCost: 30,
    execution: 'async',
    description: 'Cheap with strong physics — budget motion pick.',
  },
  {
    id: 'grok_video_v15',
    label: 'Grok Video 1.5',
    family: 'xAI',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video'],
    aspectRatios: ['16:9', '9:16'],
    durations: [2, 5, 10, 15],
    supportsAudio: false,
    maxBatch: 4,
    creditCost: 36,
    execution: 'async',
    description: 'Bold image-to-video from a required reference frame.',
  },
  // ----- Audio -----
  {
    id: 'sonilo_music',
    label: 'Sonilo Music',
    family: 'Sonilo',
    featured: false,
    kind: 'audio',
    providerKey: 'higgsfield',
    capabilities: ['generate_caption'],
    aspectRatios: [],
    durations: [8, 12, 30],
    maxBatch: 1,
    creditCost: 10,
    execution: 'async',
    description: 'Generate music from text — backing tracks, jingles, instrumental beds.',
  },
  {
    id: 'mirelo_text_to_audio',
    label: 'Mirelo Text to Audio',
    family: 'Mirelo',
    featured: false,
    kind: 'audio',
    providerKey: 'higgsfield',
    capabilities: ['generate_caption'],
    aspectRatios: [],
    durations: [4, 8],
    maxBatch: 1,
    creditCost: 6,
    execution: 'async',
    description: 'Non-speech audio — sound effects, ambience, foley, impacts.',
  },
  // ----- Text -----
  {
    id: 'agent-llm',
    label: 'LLM Assistant',
    family: 'PiB Agents',
    featured: false,
    kind: 'text',
    providerKey: 'agent_task',
    capabilities: ['generate_copy'],
    aspectRatios: [],
    maxBatch: 1,
    creditCost: 2,
    execution: 'async',
    description: 'Agent-driven LLM text assistant for prompts, copy and briefs.',
  },
]

export function getCanvasModel(id: string): CanvasModel | undefined {
  return CANVAS_MODELS.find((m) => m.id === id)
}

export function modelsForKind(kind: CanvasModel['kind']): CanvasModel[] {
  return CANVAS_MODELS.filter((m) => m.kind === kind)
}

export function featuredModels(): CanvasModel[] {
  return CANVAS_MODELS.filter((m) => m.featured)
}
