import type {
  CreativeCanvasProviderKey,
  CreativeCanvasProviderCapability,
} from '@/lib/creative-canvas/types'

export interface CanvasModel {
  id: string
  label: string
  family: string
  featured: boolean
  kind: 'image' | 'video' | 'audio' | 'text'
  providerKey: CreativeCanvasProviderKey
  capabilities: CreativeCanvasProviderCapability[]
  aspectRatios: string[]
  resolutions?: string[]
  durations?: number[]
  supportsAudio?: boolean
  maxBatch: number
  creditCost: number
  execution: 'sync' | 'async'
  description?: string
  /** true for the near-free Higgsfield-native "unlimited-tier" models */
  unlimited?: boolean
}

// The real Higgsfield model catalog. `id` is the verified Higgsfield CLI
// `job_set_type` (confirmed via `higgsfield model list` on the VPS) so the run
// manifest passes the right model. All image/video/audio models execute
// asynchronously through the Higgsfield runtime / Hermes agent (the web app
// cannot call the Higgsfield CLI directly); `agent-llm` routes through the PiB
// agent task runner.
//
// Standing policy: agents default to the low-cost Higgsfield-native
// "unlimited-tier" models (`unlimited: true`) unless explicitly told otherwise.
// Those are featured and the cheapest tier; `text2image_soul_v2` is the default.
export const CANVAS_MODELS: CanvasModel[] = [
  // ----- Image -----
  {
    id: 'text2image_soul_v2',
    label: 'Higgsfield Soul 2.0',
    family: 'Higgsfield',
    featured: true,
    unlimited: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 0.1,
    execution: 'async',
    description: 'Default image model — near-free Higgsfield-native aesthetic UGC, fashion editorial, character work. Accepts a Soul Character reference.',
  },
  {
    id: 'z_image',
    label: 'Z Image',
    family: 'Tongyi-MAI',
    featured: true,
    unlimited: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 0.15,
    execution: 'async',
    description: 'Near-free fast image model — drafts and rapid iteration.',
  },
  {
    id: 'soul_cinematic',
    label: 'Soul Cinematic',
    family: 'Higgsfield',
    featured: false,
    unlimited: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 0.2,
    execution: 'async',
    description: 'Near-free cinematic stills — film-grade lighting and concept-art mood.',
  },
  {
    id: 'cinematic_studio_image',
    label: 'Cinematic Studio Image',
    family: 'Higgsfield',
    featured: false,
    unlimited: true,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 0.2,
    execution: 'async',
    description: 'Near-free studio-grade cinematic image generation for polished marketing visuals.',
  },
  {
    id: 'nano_banana_flash',
    label: 'Nano Banana 2',
    family: 'Google',
    featured: true,
    unlimited: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 2,
    execution: 'async',
    description: 'Fast everyday Google model for character / cartoon / animated-style work.',
  },
  {
    id: 'nano_banana_2',
    label: 'Nano Banana Pro',
    family: 'Google',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 4,
    execution: 'async',
    description: 'Top-tier Nano Banana with extra fidelity on harder briefs.',
  },
  {
    id: 'seedream_v4_5',
    label: 'Seedream 4.5',
    family: 'ByteDance',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 3,
    execution: 'async',
    description: 'Complex, face-anchored scene edits.',
  },
  {
    id: 'flux_2',
    label: 'FLUX.2',
    family: 'Black Forest Labs',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 3,
    execution: 'async',
    description: 'Precise prompt adherence with pro/flex/max variants.',
  },
  {
    id: 'grok_image',
    label: 'Grok Image',
    family: 'xAI',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 3,
    execution: 'async',
    description: 'Expressive, high-contrast, bold creative outputs.',
  },
  {
    id: 'recraft_v4_1',
    label: 'Recraft V4.1',
    family: 'Recraft',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 2,
    execution: 'async',
    description: 'Brand-grade graphic design, logos, vector-style and on-image text.',
  },
  {
    id: 'kling_omni_image',
    label: 'Kling O1 Image',
    family: 'Kling',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 3,
    execution: 'async',
    description: 'Multi-reference omni image generation and editing.',
  },
  {
    id: 'gpt_image_2',
    label: 'GPT Image 2',
    family: 'OpenAI',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k', '4k'],
    maxBatch: 4,
    creditCost: 7,
    execution: 'async',
    description: 'High-fidelity image generation — graphic design, UI, banners, on-image text.',
  },
  {
    id: 'image_auto',
    label: 'Auto',
    family: 'Higgsfield',
    featured: false,
    kind: 'image',
    providerKey: 'higgsfield',
    capabilities: ['generate_image', 'edit_image', 'create_variants'],
    aspectRatios: ['1:1', '9:16', '16:9', '4:5', '3:2'],
    resolutions: ['1k', '2k'],
    maxBatch: 4,
    creditCost: 1,
    execution: 'async',
    description: 'Smart routing — picks the best image model from the prompt.',
  },
  // ----- Video -----
  {
    id: 'cinematic_studio_video_3_5',
    label: 'Cinema Studio Video 3.5',
    family: 'Higgsfield',
    featured: true,
    unlimited: true,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 3,
    execution: 'async',
    description: 'Default video model — near-free Higgsfield-native cinematic studio video.',
  },
  {
    id: 'seedance1_5',
    label: 'Seedance 1.5',
    family: 'ByteDance',
    featured: true,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 5,
    execution: 'async',
    description: 'All-purpose video — crisp, consistent identity, multi-shot.',
  },
  {
    id: 'minimax_hailuo',
    label: 'Minimax Hailuo',
    family: 'Hailuo',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: false,
    maxBatch: 4,
    creditCost: 6,
    execution: 'async',
    description: 'Strong physics — budget motion pick.',
  },
  {
    id: 'kling3_0',
    label: 'Kling 3.0',
    family: 'Kling',
    featured: true,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 18,
    execution: 'async',
    description: 'High-quality video with audio sync and motion transfer.',
  },
  {
    id: 'kling3_0_turbo',
    label: 'Kling 3.0 Turbo',
    family: 'Kling',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 10,
    execution: 'async',
    description: 'Faster, cheaper Kling 3.0 variant.',
  },
  {
    id: 'veo3_1',
    label: 'Google Veo 3.1',
    family: 'Google',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 30,
    execution: 'async',
    description: 'Ultra-realistic, top-tier cinematic quality with audio.',
  },
  {
    id: 'veo3_1_lite',
    label: 'Veo 3.1 Lite',
    family: 'Google',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 12,
    execution: 'async',
    description: 'Cheaper Veo 3.1 variant with audio.',
  },
  {
    id: 'grok_video_v15',
    label: 'Grok Video 1.5',
    family: 'xAI',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [2, 5, 10, 15],
    supportsAudio: false,
    maxBatch: 4,
    creditCost: 8,
    execution: 'async',
    description: 'Bold image-to-video from a reference frame.',
  },
  {
    id: 'marketing_studio_video',
    label: 'Marketing Studio',
    family: 'Higgsfield',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 8,
    execution: 'async',
    description: 'Marketing-focused product and brand video generation.',
  },
  {
    id: 'seedance_2_0',
    label: 'Seedance 2.0',
    family: 'ByteDance',
    featured: false,
    kind: 'video',
    providerKey: 'higgsfield',
    capabilities: ['generate_video', 'edit_video'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    durations: [4, 8, 10, 15],
    supportsAudio: true,
    maxBatch: 4,
    creditCost: 22,
    execution: 'async',
    description: 'SOTA all-purpose video — crisp, consistent identity, multi-shot.',
  },
  // ----- Audio -----
  {
    id: 'sonilo_music',
    label: 'Sonilo Music',
    family: 'Sonilo',
    featured: false,
    unlimited: true,
    kind: 'audio',
    providerKey: 'higgsfield',
    capabilities: ['generate_caption'],
    aspectRatios: [],
    durations: [8, 12, 30],
    maxBatch: 1,
    creditCost: 1,
    execution: 'async',
    description: 'Near-free music from text — backing tracks, jingles, instrumental beds.',
  },
  {
    id: 'mirelo_text_to_audio',
    label: 'Mirelo Text to Audio',
    family: 'Mirelo',
    featured: false,
    kind: 'audio',
    providerKey: 'higgsfield',
    capabilities: ['generate_caption'],
    aspectRatios: [],
    durations: [4, 8],
    maxBatch: 1,
    creditCost: 1,
    execution: 'async',
    description: 'Non-speech audio — sound effects, ambience, foley, impacts.',
  },
  // ----- Text -----
  {
    id: 'agent-llm',
    label: 'LLM Assistant',
    family: 'PiB Agents',
    featured: false,
    kind: 'text',
    providerKey: 'agent_task',
    capabilities: ['generate_copy'],
    aspectRatios: [],
    maxBatch: 1,
    creditCost: 1,
    execution: 'async',
    description: 'Agent-driven LLM text assistant for prompts, copy and briefs.',
  },
]

export function getCanvasModel(id: string): CanvasModel | undefined {
  return CANVAS_MODELS.find((m) => m.id === id)
}

export function modelsForKind(kind: CanvasModel['kind']): CanvasModel[] {
  return CANVAS_MODELS.filter((m) => m.kind === kind)
}

export function featuredModels(): CanvasModel[] {
  return CANVAS_MODELS.filter((m) => m.featured)
}
